name: Predict if mergeable or not

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  predict:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install boto3 botocore

      - name: Check mergeability via SageMaker API
        id: predicter
        env:
          ENDPOINT_NAME: pr-classifier-endpoint-v2
        run: |
          import boto3, json, os
          from botocore.config import Config

          config = Config(read_timeout=300, connect_timeout=60)
          client = boto3.client("sagemaker-runtime", region_name="eu-north-1", config=config)

          pr_text = """${{ github.event.pull_request.body }}""" or "No description provided."
          payload = {"text": pr_text}

          response = client.invoke_endpoint(
              EndpointName=os.environ["ENDPOINT_NAME"],
              ContentType="application/json",
              Body=json.dumps(payload)
          )
          result = json.loads(response["Body"].read().decode("utf-8"))
          mergeable = result.get("prediction", "False")
          print("mergeable:", mergeable)

          with open(os.environ["GITHUB_OUTPUT"], "a") as gh_out:
              gh_out.write(f"mergeable={mergeable}\n")
        shell: python

      - name: Remove 'mergeable' & 'not-mergeable' labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            mergeable
            not-mergeable

      - name: If mergeable
        if: ${{ startsWith(steps.predicter.outputs.mergeable, 'True') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mergeable

      - name: If not mergeable
        if: ${{ startsWith(steps.predicter.outputs.mergeable, 'False') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: not-mergeable
